name: game_tetris
description: Tetris game package for FunBox.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/images/
